// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type {
  SQLTypeMarker,
  SQLStringMarker,
  SQLNumberMarker,
  SQLBooleanMarker,
  SQLBinaryMarker,
  SQLDateMarker,
  SQLTimestampMarker,
} from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    content_overview: {
      name: "content_overview";
      parameters: Record<string, never>;
      result: Array<{
        /** @sqlType BIGINT */
        total_submissions: number;
        /** @sqlType BIGINT */
        pending_count: number;
        /** @sqlType BIGINT */
        approved_count: number;
        /** @sqlType BIGINT */
        rejected_count: number;
        /** @sqlType BIGINT */
        revision_count: number;
        /** @sqlType DOUBLE */
        avg_compliance_score: number;
      }>;
    };
    submissions_by_target: {
      name: "submissions_by_target";
      parameters: Record<string, never>;
      result: Array<{
        /** @sqlType STRING */
        target: string;
        /** @sqlType BIGINT */
        submission_count: number;
        /** @sqlType BIGINT */
        approved_count: number;
        /** @sqlType DOUBLE */
        avg_score: number;
      }>;
    };
  }
}
