// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import '@databricks/appkit-ui/react';
import type {
  SQLTypeMarker,
  SQLStringMarker,
  SQLNumberMarker,
  SQLBooleanMarker,
  SQLBinaryMarker,
  SQLDateMarker,
  SQLTimestampMarker,
} from '@databricks/appkit-ui/js';

declare module '@databricks/appkit-ui/react' {
  interface QueryRegistry {
    agent_performance: {
      name: 'agent_performance';
      parameters: Record<string, never>;
      result: Array<{
        /** @sqlType STRING */
        action: string;
        /** @sqlType BIGINT */
        count: number;
        /** @sqlType DOUBLE */
        avg_amount_cents: number;
      }>;
    };
    support_metrics: {
      name: 'support_metrics';
      parameters: Record<string, never>;
      result: Array<{
        /** @sqlType DATE */
        case_date: string;
        /** @sqlType BIGINT */
        total_cases: number;
        /** @sqlType BIGINT */
        open_cases: number;
        /** @sqlType BIGINT */
        resolved_cases: number;
        /** @sqlType DOUBLE */
        avg_messages_per_case: number;
        /** @sqlType DOUBLE */
        avg_first_response_minutes: number;
        /** @sqlType BIGINT */
        cases_with_refund: number;
        /** @sqlType BIGINT */
        cases_with_credit: number;
        /** @sqlType BIGINT */
        total_refund_cents: number;
        /** @sqlType BIGINT */
        total_credit_cents: number;
      }>;
    };
  }
}
