command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: "OBO_ENABLED"
    value: False
  - name: "SERVING_ENDPOINT"
    valueFrom: "serving-endpoint"
    # value: "<if OBO-user, comment out above line, uncomment this, and enter your serving endpoint name here>"
