// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type {
  SQLTypeMarker,
  SQLStringMarker,
  SQLNumberMarker,
  SQLBooleanMarker,
  SQLBinaryMarker,
  SQLDateMarker,
  SQLTimestampMarker,
} from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    spend_overview: {
      name: "spend_overview";
      parameters: Record<string, never>;
      result: Array<{
        /** @sqlType BIGINT */
        active_count: number;
        /** @sqlType BIGINT */
        cancelled_count: number;
        /** @sqlType BIGINT */
        monthly_spend_cents: number;
        /** @sqlType BIGINT */
        annual_spend_cents: number;
        /** @sqlType BIGINT */
        renewals_next_30d: number;
      }>;
    };
    spend_by_category: {
      name: "spend_by_category";
      parameters: Record<string, never>;
      result: Array<{
        /** @sqlType STRING */
        category: string;
        /** @sqlType BIGINT */
        subscription_count: number;
        /** @sqlType BIGINT */
        monthly_spend_cents: number;
      }>;
    };
  }
}
