packages:
  - client
  - server
  - packages/*

catalog:
  "@types/node": ^22.8.6
  "@ai-sdk/react": ^2.0.76
  "@ai-sdk/provider": ^2.0.0
  "@ai-sdk/provider-utils": ^3.0.12
  ai: ^5.0.76
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.44.6
  postgres: ^3.4.4
  tsdown: 0.15.9
  typescript: ^5.9.3
  zod: ^3.25.76
