command: ["uv", "run", "custom-open-api-spec-server"]

env:
  - name: "MLFLOW_TRACKING_URI"
    value: "databricks"
  - name: "MLFLOW_EXPERIMENT_ID"
    valueFrom: "mlflow-experiment"
  - name: "MLFLOW_TRACING_SQL_WAREHOUSE_ID"
    valueFrom: "mlflow-tracing-warehouse"
  - name: "MLFLOW_UC_CATALOG"
    value: "main"
  - name: "MLFLOW_UC_SCHEMA"
    value: "agent_traces"
  - name: "MLFLOW_UC_TABLE_PREFIX"
    value: "mcp_openapi_spec"
  - name: "MLFLOW_OTEL_SPANS_TABLE"
    value: "main.agent_traces.mcp_openapi_spec_otel_spans"
  - name: "UC_CONNECTION_NAME"
    value: "" # TODO: Add the connection name
  - name: "SPEC_FILE_NAME"
    value: "spec.json"            # TODO: Update the spec file name if different from spec.json
  - name: "SPEC_VOLUME_PATH"
    valueFrom: "uc-volume"
