import json
import logging
from typing import Any, AsyncGenerator, AsyncIterator, Optional
from uuid import uuid4

from databricks.sdk import WorkspaceClient
from google.adk.events import Event
from google.adk.sessions import BaseSessionService
from google.genai import types
from mlflow.genai.agent_server import get_request_headers
from mlflow.types.responses import (
    ResponsesAgentRequest,
    ResponsesAgentStreamEvent,
    create_function_call_item,
    create_function_call_output_item,
    create_text_delta,
    create_text_output_item,
)

logger = logging.getLogger(__name__)


def get_session_id(request: ResponsesAgentRequest) -> str | None:
    if request.context and request.context.conversation_id:
        return request.context.conversation_id
    if request.custom_inputs and isinstance(request.custom_inputs, dict):
        return request.custom_inputs.get("session_id")
    return None


def get_user_workspace_client() -> WorkspaceClient:
    token = get_request_headers().get("x-forwarded-access-token")
    return WorkspaceClient(token=token, auth_type="pat")


def get_databricks_host(workspace_client: WorkspaceClient | None = None) -> Optional[str]:
    try:
        w = workspace_client or WorkspaceClient()
        return w.config.host
    except Exception as e:
        logger.exception(f"Error getting databricks host from env: {e}")
        return None


def get_bearer_token(workspace_client: WorkspaceClient) -> str:
    """Extract a bearer token from the Databricks SDK credential chain.

    Works for every SDK auth flow (CLI profile, PAT, and the OAuth service-principal
    credentials injected into Databricks Apps). LiteLLM needs a concrete ``api_key`` to
    call the model serving OpenAI-compatible endpoint, so we resolve one per request.
    """
    auth_header = workspace_client.config.authenticate().get("Authorization", "")
    return auth_header.removeprefix("Bearer ").strip()


def _content_to_text(content: Any) -> str:
    """Flatten a Responses/chat message ``content`` (str or list of parts) into plain text."""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for part in content:
            if isinstance(part, dict):
                parts.append(part.get("text") or part.get("content") or "")
            elif isinstance(part, str):
                parts.append(part)
        return "".join(parts)
    return "" if content is None else str(content)


async def seed_session_history(
    session_service: BaseSessionService,
    app_name: str,
    user_id: str,
    session_id: str,
    messages: list[dict[str, Any]],
    agent_name: str,
) -> types.Content:
    """Create a session, replay prior conversation turns into it, and return the new message.

    This template is stateless — the client carries the full conversation in ``request.input``.
    ADK's Runner, by contrast, loads history from its SessionService and only takes the latest
    turn as ``new_message``. So we materialize the prior turns as session events and hand ADK the
    final user turn to act on. Returns the ``types.Content`` for the latest user message.
    """
    session = await session_service.create_session(
        app_name=app_name, user_id=user_id, session_id=session_id
    )

    # The last user message is the turn the agent should act on; everything before it is history.
    # Guard against payloads that don't end on a user turn so an assistant/tool message is never
    # replayed as the user's new message.
    user_indices = [i for i, m in enumerate(messages) if m.get("role") == "user"]
    if user_indices:
        latest_idx = user_indices[-1]
        history = messages[:latest_idx]
        latest_text = _content_to_text(messages[latest_idx].get("content"))
    else:
        history = messages[:-1]
        latest_text = _content_to_text(messages[-1].get("content")) if messages else ""

    for msg in history:
        role = msg.get("role")
        text = _content_to_text(msg.get("content"))
        if not text:
            continue
        if role == "user":
            author, content_role = "user", "user"
        elif role == "assistant":
            author, content_role = agent_name, "model"
        else:
            # system prompts are supplied via the agent's `instruction`; tool turns are
            # regenerated by the agent, so they are not replayed here.
            continue
        await session_service.append_event(
            session,
            Event(
                author=author,
                content=types.Content(role=content_role, parts=[types.Part(text=text)]),
            ),
        )

    return types.Content(role="user", parts=[types.Part(text=latest_text)])


async def process_adk_events(
    async_stream: AsyncIterator[Event],
) -> AsyncGenerator[ResponsesAgentStreamEvent, None]:
    """Adapt Google ADK ``Event`` objects into MLflow ``ResponsesAgentStreamEvent`` objects.

    Emits:
      - ``response.output_text.delta`` for streamed token chunks (``event.partial``),
      - ``response.output_item.done`` message items for completed assistant text,
      - ``response.output_item.done`` function_call / function_call_output items for tool use.
    """
    text_item_id = str(uuid4())
    # ADK normally sets FunctionCall.id / FunctionResponse.id and they match. If a null id ever
    # slips through, fall back to a synthesized id shared between a call and its response (matched
    # FIFO by tool name) so the pair never desyncs.
    synthesized_call_ids: dict[str, list[str]] = {}
    async for event in async_stream:
        # Tool calls and their results only appear on complete (non-partial) events.
        if not event.partial:
            for fc in event.get_function_calls():
                call_id = fc.id
                if not call_id:
                    call_id = str(uuid4())
                    synthesized_call_ids.setdefault(fc.name, []).append(call_id)
                yield ResponsesAgentStreamEvent(
                    type="response.output_item.done",
                    item=create_function_call_item(
                        id=call_id,
                        call_id=call_id,
                        name=fc.name,
                        arguments=json.dumps(fc.args or {}),
                    ),
                )
            for fr in event.get_function_responses():
                call_id = fr.id
                if not call_id:
                    queue = synthesized_call_ids.get(fr.name)
                    call_id = queue.pop(0) if queue else str(uuid4())
                # ADK wraps a tool's non-dict return value as ``{"result": <value>}``. Unwrap that
                # single-key form so tool outputs match the other templates (a bare string for a
                # scalar return, not a JSON object) for clients and downstream parsing; pass any
                # other shape through as JSON.
                resp = fr.response
                if isinstance(resp, str):
                    output = resp
                elif isinstance(resp, dict) and set(resp) == {"result"}:
                    inner = resp["result"]
                    output = inner if isinstance(inner, str) else json.dumps(inner)
                else:
                    output = json.dumps(resp)
                yield ResponsesAgentStreamEvent(
                    type="response.output_item.done",
                    item=create_function_call_output_item(
                        call_id=call_id,
                        output=output,
                    ),
                )

        # Assistant text: skip reasoning ("thought") parts.
        if not (event.content and event.content.parts):
            continue
        text = "".join(p.text for p in event.content.parts if p.text and not p.thought)
        if not text:
            continue

        if event.partial:
            yield ResponsesAgentStreamEvent(
                **create_text_delta(delta=text, item_id=text_item_id)
            )
        else:
            yield ResponsesAgentStreamEvent(
                type="response.output_item.done",
                item=create_text_output_item(text=text, id=text_item_id),
            )
            # Rotate the id so a subsequent assistant message is a distinct output item.
            text_item_id = str(uuid4())
