// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import '@databricks/appkit-ui/react';
import type {
  SQLTypeMarker,
  SQLStringMarker,
  SQLNumberMarker,
  SQLBooleanMarker,
  SQLBinaryMarker,
  SQLDateMarker,
  SQLTimestampMarker,
} from '@databricks/appkit-ui/js';

declare module '@databricks/appkit-ui/react' {
  interface QueryRegistry {
    booking_detail: {
      name: 'booking_detail';
      parameters: {
        /** NUMERIC - use sql.number() */
        bookingId: SQLNumberMarker;
      };
      result: Array<{
        /** Unique identifier of the booking */
        booking_id: number;
        /** Status of the booking (e.g., pending, confirmed) */
        status: string;
        /** Check-in date */
        check_in: string;
        /** Check-out date */
        check_out: string;
        /** Number of guests for booking */
        guests_count: number;
        /** Total amount paid */
        total_amount: number;
        /** Name of the user. */
        guest_name: string;
        /** User's email address. */
        guest_email: string;
        /** Title of the property listing */
        property_title: string;
        /** Name of the destination */
        destination: string;
      }>;
    };
    revenue_by_destination: {
      name: 'revenue_by_destination';
      parameters: {
        /** NUMERIC - use sql.number() */
        limit: SQLNumberMarker;
      };
      result: Array<{
        /** Name of the destination */
        destination: string;
        /** Name of the country */
        country: string;
        /** @sqlType BIGINT */
        total_bookings: number;
        /** @sqlType DOUBLE */
        total_revenue: number;
        /** @sqlType DOUBLE */
        avg_rating: number;
      }>;
    };
  }
}
