name: Test All Apps

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests script
        run: ./scripts/test_apps.sh
